//Ingredients
export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";

//Ingredient Details
export const OPEN_INGREDIENT_DETAILS = "OPEN_INGREDIENT_DETAILS";
export const CLOSE_INGREDIENT_DETAILS = "CLOSE_INGREDIENT_DETAILS";

// Burger Constructor
export const ADD_BURGER_INGREDIENT = "ADD_BURGER_INGREDIENT";
export const REMOVE_BURGER_INGREDIENT = "REMOVE_BURGER_INGREDIENT";
export const MOVE_NOTBUNS_INGREDIENT = 'MOVE_NOTBUNS_INGREDIENT';

// Place Order
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";

//Order Detailes 
export const CLOSE_ORDER_DETAILS = "CLOSE_ORDER_DETAILS";

export const BASE_URL = "https://norma.nomoreparties.space/api/";

// Auth
export const PASSWORD_RESET_PENDING = "PASSWORD_RESET_PENDING"
export const CLEAR_PASSWORD_RESET = "CLEAR_PASSWORD_RESET"
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT_USER = "LOGOUT_USER";