export const BASE_URL = "https://norma.nomoreparties.space/api/";
// Ingredients
export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR" = "GET_INGREDIENTS_ERROR";

// Ingredient Details
export const OPEN_INGREDIENT_DETAILS: "OPEN_INGREDIENT_DETAILS" = "OPEN_INGREDIENT_DETAILS";
export const CLOSE_INGREDIENT_DETAILS: "CLOSE_INGREDIENT_DETAILS" = "CLOSE_INGREDIENT_DETAILS";

// Burger Constructor
export const ADD_BURGER_INGREDIENT: "ADD_BURGER_INGREDIENT" = "ADD_BURGER_INGREDIENT";
export const REMOVE_BURGER_INGREDIENT: "REMOVE_BURGER_INGREDIENT" = "REMOVE_BURGER_INGREDIENT";
export const MOVE_NOTBUNS_INGREDIENT: "MOVE_NOTBUNS_INGREDIENT" = "MOVE_NOTBUNS_INGREDIENT";

// Place Order
export const PLACE_ORDER_REQUEST: "PLACE_ORDER_REQUEST" = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS: "PLACE_ORDER_SUCCESS" = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR: "PLACE_ORDER_ERROR" = "PLACE_ORDER_ERROR";

// Order Details
export const CLOSE_ORDER_DETAILS: "CLOSE_ORDER_DETAILS" = "CLOSE_ORDER_DETAILS";

// Auth
export const PASSWORD_RESET_PENDING: "PASSWORD_RESET_PENDING" = "PASSWORD_RESET_PENDING";
export const CLEAR_PASSWORD_RESET: "CLEAR_PASSWORD_RESET" = "CLEAR_PASSWORD_RESET";
export const REGISTER_USER: "REGISTER_USER" = "REGISTER_USER";
export const LOGIN_USER: "LOGIN_USER" = "LOGIN_USER";
export const SET_USER: "SET_USER" = "SET_USER";
export const UPDATE_USER: "UPDATE_USER" = "UPDATE_USER";
export const LOGOUT_USER: "LOGOUT_USER" = "LOGOUT_USER";

export type TActionType =
    | typeof GET_INGREDIENTS_REQUEST
    | typeof GET_INGREDIENTS_SUCCESS
    | typeof GET_INGREDIENTS_ERROR
    | typeof OPEN_INGREDIENT_DETAILS
    | typeof CLOSE_INGREDIENT_DETAILS
    | typeof ADD_BURGER_INGREDIENT
    | typeof REMOVE_BURGER_INGREDIENT
    | typeof MOVE_NOTBUNS_INGREDIENT
    | typeof PLACE_ORDER_REQUEST
    | typeof PLACE_ORDER_SUCCESS
    | typeof PLACE_ORDER_ERROR
    | typeof CLOSE_ORDER_DETAILS
    | typeof PASSWORD_RESET_PENDING
    | typeof CLEAR_PASSWORD_RESET
    | typeof REGISTER_USER
    | typeof LOGIN_USER
    | typeof SET_USER
    | typeof UPDATE_USER
    | typeof LOGOUT_USER;
